apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: pwn5q175c-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/pwn5q175c-java-quarkus-gitops