apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pwn5q175c-java-quarkus
  janus-idp.io/tekton: pwn5q175c-java-quarkus
  backstage.io/kubernetes-id: pwn5q175c-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pwn5q175c-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
